-- simple lua script that reads out.json (which should have been generated by bb2json.py)
-- and stores it in the focal port placed below
local p = peripheral.find("focal_port")
local f = fs.open(...,"r")
local d = f.readAll()
f.close()
local dat = textutils.unserializeJSON(d)
p.writeIota(dat)
